coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        informational: true
    patch:
      default:
        informational: true

ignore:
  - "tests/"
  - "**/__init__.py"
