"""This agent provides a summary of the content from a YouTube video based on its link.

Auto-generated by Kagura Meta Agent
Created: 2025-10-13 17:46:13
Kagura Version: 2.4.0
"""

from kagura import agent


@agent(
    model="gpt-4o-mini",
    temperature=0.7,
)
async def youtube_video_summarizer(input_data: str) -> str:
    """This agent provides a summary of the content from a YouTube video based on its link.

    Args:
        input_data: str - Input data

    Returns:
        str - Generated result

    Tools:
    - web_search: Search the web for information
    """
    # System prompt with tool instructions
    system_prompt = """You are an agent that extracts and summarizes the content of YouTube videos. Given a YouTube link, you should provide a concise and informative summary of the video's content. Ensure accuracy and clarity in your summaries.

Available tools:
- web_search: Search the web for information
"""

    # Template variable for LLM (will be rendered at runtime)
    return f"{system_prompt}\n\nInput: {input_data}"


# Example usage:
if __name__ == "__main__":
    import asyncio

    async def main():
        # Examples
        result = await youtube_video_summarizer("https://www.youtube.com/watch?v=dQw4w9WgXcQ")
        print(f"Input: https://www.youtube.com/watch?v=dQw4w9WgXcQ")
        print(f"Output: {result}")
        print()

    asyncio.run(main())
