name: Deploy MkDocs
on:
  push:
    paths:
      - "docs/**"
      - ".github/workflows/deploy_mkdocs.yml"
      - "mkdocs.yml"
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Setup caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/uv
            ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Install dependencies
        run: |
          uv sync --frozen --all-extras --dev

      - name: Create CNAME file
        run: echo "www.kagura-ai.com" > docs/CNAME

      - name: Deploy to GitHub Pages
        run: uv run mkdocs gh-deploy --force
